name: Compile and Test on Linux

on:
  push:
    branches: [ main, develop, test ]
    paths-ignore: &paths-ignore
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/api.yml"
      - ".github/workflows/ios.yml"
      - ".github/workflows/macos.yml"
  pull_request:
    branches: [ main, develop, test ]
    paths-ignore: *paths-ignore
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout enrouteOGN
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Compile and Test
      run: |
        ./build-and-test.sh
    - name: Run Code Checks
      run: |
        ./codechecks.sh
